### ISSUE TITLE
When i cancel the add to WhatsApp request it's forced close the app and the app exists

### ISSUE THREAD

**Issue by Kinoshan** [viztushar/flutter_whatsapp_stickers_internet#7]
D/AndroidRuntime(28376): Shutting down VM
E/AndroidRuntime(28376): FATAL EXCEPTION: main
E/AndroidRuntime(28376): Process: com.viztushar.flutter.flutter_stickers_internet, PID: 28376
E/AndroidRuntime(28376): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=200, result=0, data=null} to activity {com.viztushar.flutter.flutter_stickers_internet/com.viztushar.flutter.flutter_stickers_internet.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(28376):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5156)
E/AndroidRuntime(28376):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5197)
E/AndroidRuntime(28376):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(28376):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(28376):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(28376):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
E/AndroidRuntime(28376):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28376):        at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(28376):        at android.app.ActivityThread.main(ActivityThread.java:8059)
E/AndroidRuntime(28376):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28376):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(28376):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(28376): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(28376):        at com.viztushar.flutter.flutter_stickers_internet.MainActivity.onActivityResult(Unknown Source:2)
E/AndroidRuntime(28376):        at android.app.Activity.dispatchActivityResult(Activity.java:8524)
E/AndroidRuntime(28376):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5149)
E/AndroidRuntime(28376):        ... 11 more
D/OOMEventManagerFK(28376): checkEventAndDumpForJE: 0
I/Process (28376): Sending signal. PID: 28376 SIG: 9
Lost connection to device.

**Comment by Kinoshan** [comment]
OK! i found the problem and it's solved 

change the onactivity intent to intent? it's non-nullable value

Before :

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == ADD_PACK) {
            if (resultCode == Activity.RESULT_CANCELED && data != null) {
                val validationError = data.getStringExtra("validation_error")
                if (validationError != null) {
                    if (BuildConfig.DEBUG) {
                        //validation error should be shown to developer only, not users.
                        //MessageDialogFragment.newInstance(R.string.title_validation_error, validationError).show(getSupportFragmentManager(), "validation error");
                    }
                    Log.e(TAG, "Validation failed:$validationError")
                }
            }
        }
    }

After FIX!

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == ADD_PACK) {
            if (resultCode == Activity.RESULT_CANCELED && data != null) {
                val validationError = data.getStringExtra("validation_error")
                if (validationError != null) {
                    if (BuildConfig.DEBUG) {
                        //validation error should be shown to developer only, not users.
                        //MessageDialogFragment.newInstance(R.string.title_validation_error, validationError).show(getSupportFragmentManager(), "validation error");
                    }
                    Log.e(TAG, "Validation failed:$validationError")
                }
            }
        }
    }

it's working for me 👍
